includes: [./paths.yml, 'sequences/{Sequence}/{Shot}/tank_overrides.yml', 'assets/{sg_asset_type}/{Asset}/tank_overrides.yml']
launch_hiero:
  engine: tk-hiero
  extra: {}
  hook_app_launch: default
  hook_before_app_launch: default
  linux_args: ''
  linux_path: '@hiero_linux'
  location: {name: tk-multi-launchapp, type: app_store, version: v0.2.12}
  mac_args: ''
  mac_path: '@hiero_mac'
  menu_name: Launch Hiero
  windows_args: ''
  windows_path: '@hiero_windows'
launch_maya:
  engine: tk-maya
  extra: {}
  hook_app_launch: app_launch
  hook_before_app_launch: default
  linux_args: ''
  linux_path: '@maya_linux'
  location: {name: tk-multi-launchapp, type: app_store, version: v0.2.12}
  mac_args: ''
  mac_path: '@maya_mac'
  menu_name: Launch Maya
  windows_args: ''
  windows_path: '@maya_windows'
launch_nuke:
  engine: tk-nuke
  extra: {}
  hook_app_launch: default
  hook_before_app_launch: before_app_launch
  linux_args: ''
  linux_path: '@nuke_linux'
  location: {name: tk-multi-launchapp, type: app_store, version: v0.2.12}
  mac_args: ''
  mac_path: '@nuke_mac'
  menu_name: Launch Nuke
  windows_args: ''
  windows_path: '@nuke_windows'
launch_nukeX:
  engine: tk-nuke
  extra: {}
  hook_app_launch: default
  hook_before_app_launch: default
  linux_args: ''
  linux_path: '@nuke_linux'
  location: {name: tk-multi-launchapp, type: app_store, version: v0.2.12}
  mac_args: ''
  mac_path: '@nuke_mac'
  menu_name: Launch NukeX
  windows_args: '--nukex'
  windows_path: '@nuke_windows'
launch_photoshop:
  engine: tk-photoshop
  extra: '@photoshop_extras'
  hook_app_launch: default
  hook_before_app_launch: default
  linux_args: ''
  linux_path: ''
  location: {name: tk-multi-launchapp, type: app_store, version: v0.2.12}
  mac_args: ''
  mac_path: '@photoshop_mac'
  menu_name: Launch Photoshop
  windows_args: ''
  windows_path: '@photoshop_win'
launch_screeningroom:
  location: {name: tk-multi-screeningroom, type: app_store, version: v0.1.5}
  rv_path_linux: '@rv_linux'
  rv_path_mac: '@rv_mac'
  rv_path_windows: '@rv_win'
launch_shotgun_screeningroom:
  deny_permissions: []
  deny_platforms: []
  location: {name: tk-shotgun-launchscreeningroom, type: app_store, version: v0.1.6}
  rv_path_linux: '@rv_linux'
  rv_path_mac: '@rv_mac'
  rv_path_windows: '@rv_win'
