################################################################################################
#
# Tank Default VFX Configuration
#

# this file defines paths to key applications for this project


#
# maya
#
maya_windows: 'C:\Program Files\Autodesk\Maya2014\bin\maya.exe'
maya_mac: /Applications/Autodesk/maya2014/Maya.app
maya_linux: maya


#
# nuke
#
nuke_mac: /Applications/Nuke7.0v8/Nuke7.0v8.app
nuke_windows: 'C:\Program Files\Nuke7.0v8\Nuke7.0.exe'
nuke_linux: Nuke7.0

#
# hiero
#
hiero_mac: /Applications/Hiero1.7v2/Hiero1.7v2.app
hiero_windows: 'C:\Program Files\The Foundry\Hiero1.7v2\hiero.exe'
hiero_linux: Hiero1.7v2

#
# photoshop CS5.5
#
photoshop_mac: /Applications/Adobe Photoshop CS6/Adobe Photoshop CS6.app
photoshop_win: 'C:\Program Files\Adobe\Adobe Photoshop CS5.1 (64 Bit)\Photoshop.exe'
photoshop_extras:         
    mac_extension_manager_path: /Applications/Adobe Extension Manager CS6/Adobe Extension Manager CS6.app
    mac_python_path: /usr/bin/python
    windows_extension_manager_path: 'C:\Program Files (x86)\Adobe\Adobe Extension Manager CS5.5\XManCommand.exe'
    windows_python_path: 'C:\Python26\python.exe'


#
# Tweak RV
#
rv_mac: /Applications/RV64.app
rv_win: C:\Program Files\RV\RV64.exe
rv_linux: rv

