# Shotgun Pipeline Toolkit configuration file
# This file was automatically created by tank clone
# This file reflects the paths in the pipeline configuration
# entity which is associated with this location (Grandpa dev).

Windows: 'K:\Tank\00719_grandpa\dev'
Darwin: '/core/Tank/00719_grandpa\dev'
Linux: ''

# End of file.
