description: Apps and Engines related to Shot based work.
engines:
  tk-shell:
    apps:
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.10}
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-shotgun-launchmaya: '@launch_maya'
      tk-shotgun-launchnuke: '@launch_nuke'
      tk-shotgun-launchphotoshop: '@launch_photoshop'
    debug_logging: false
    location: {name: tk-shell, type: app_store, version: v0.3.1}
frameworks:
  tk-framework-widget_v0.1.1:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.1}
  tk-framework-widget_v0.1.10:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.10}
  tk-framework-widget_v0.1.12:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.12}
  tk-framework-widget_v0.1.13:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.13}
  tk-framework-widget_v0.1.15:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.15}
  tk-framework-widget_v0.1.3:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.3}
  tk-framework-widget_v0.1.4:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.4}
  tk-framework-widget_v0.1.5:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.5}
include: ./includes/app_launchers.yml
