description: Apps and Engines related to Shot based work.
engines:
  tk-maya:
    apps:
      tk-maya-breakdown:
        hook_multi_update: maya_breakdown_update
        hook_scan_scene: maya_breakdown_scan_scene
        location: {name: tk-maya-breakdown, type: app_store, version: v0.2.13}
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.14}
      tk-multi-loader-assets:
        button_name: Load Selected Item
        dependency_mode: false
        hook_add_file_to_scene: multi_add_file_to_scene
        location: {name: tk-multi-loader, type: app_store, version: v0.2.18}
        menu_name: Load Assets...
        publish_filters: []
        sg_entity_types:
          Asset: []
        single_select: true
        tank_types: [Maya Model, Maya Shaded Model, Maya Rig, Maya Lighting, Maya
            Scene]
        title_name: Add items to your Scene
      tk-multi-loader-shots:
        button_name: Load Selected Item
        dependency_mode: false
        hook_add_file_to_scene: multi_add_file_to_scene
        location: {name: tk-multi-loader, type: app_store, version: v0.2.18}
        menu_name: Load Shot Publishes...
        publish_filters: []
        sg_entity_types:
          Shot: []
        single_select: true
        tank_types: [Maya Camera, Maya Anim, Maya Sim, Maya Lighting, Maya Scene,
          Alembic Animation, Alembic Simulation]
        title_name: Add items to your Scene
      tk-multi-publish-shot:
        display_name: Publish Shot
        hook_copy_file: default
        hook_post_publish: default
        hook_primary_pre_publish: shot_asset_primary_pre_publish_tk-maya
        hook_primary_publish: shot_primary_publish
        hook_scan_scene: shot_scan_scene_tk-maya
        hook_secondary_pre_publish: shot_secondary_pre_publish_tk-maya
        hook_secondary_publish: shot_secondary_publish_tk-maya
        hook_thumbnail: default
        location: {name: tk-multi-publish, type: app_store, version: v0.3.15}
        primary_description: Publish and version up the current Maya scene
        primary_display_name: Maya Publish
        primary_icon: icons/publish_maya_main.png
        primary_publish_template: maya_shot_publish
        primary_scene_item_type: work_file
        primary_tank_type: Maya Scene
        secondary_outputs:
        - {description: Publish Alembic cache., display_group: Assets, display_name: Alembic
            Geometry, icon: icons/alembic_output.png, name: alembic_asset, publish_template: cache_alembic,
          required: false, scene_item_type: asset, selected: false, tank_type: Alembic
            Cache}
        - {description: Publish Alembic cache., display_group: Cameras, display_name: Alembic
            Camera, icon: icons/alembic_output.png, name: alembic_camera, publish_template: cache_alembic,
          required: false, scene_item_type: shotcam, selected: false, tank_type: Alembic
            Cache}
        - {description: Choose cameras for Playblast, display_group: Review, display_name: Playblast,
          icon: icons/playblast_publish.png, name: review, publish_template: maya_shot_review,
          required: false, scene_item_type: shotcam, selected: false, tank_type: Review
            Quicktime}
        - {description: Publish Alembic cache., display_group: Geometry, display_name: Alembic
            Geometry, icon: icons/alembic_output.png, name: alembic_geometry, publish_template: cache_alembic,
          required: false, scene_item_type: geometry, selected: false, tank_type: Alembic
            Cache}
        - {description: Sends Ass export and Arnold render to the farm., display_group: Render,
          display_name: Arnold Render, icon: icons/arnold.png, name: arnold_render,
          publish_template: maya_shot_review, required: false, scene_item_type: render,
          selected: false, tank_type: Arnold Render}
        - {description: Send Maya render to the farm., display_group: Render, display_name: Maya
            Render, icon: icons/maya.png, name: maya_render, publish_template: maya_shot_review,
          required: false, scene_item_type: render, selected: false, tank_type: Maya
            Render}
        - {description: Exports Ass locally and sends Arnold render to the farm.,
          display_group: Render, display_name: ASS Render, icon: icons/ass.png, name: ass_render,
          publish_template: maya_shot_review, required: false, scene_item_type: render,
          selected: false, tank_type: Arnold Render}
        template_work: maya_shot_work
      tk-multi-recentfiles:
        hook_add_file_to_scene: default
        launch_at_startup: false
        location: {name: tk-multi-recentfiles, type: app_store, version: v0.2.11}
        template_work: maya_shot_work
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-setcontext:
        enable_create_tasks: true
        launch_at_startup: false
        location: {name: tk-multi-setcontext, type: app_store, version: v0.2.7}
        sg_entity_types: [Shot]
      tk-multi-setframerange:
        location: {name: tk-multi-setframerange, type: app_store, version: v0.1.7}
        sg_in_frame_field: sg_cut_in
        sg_out_frame_field: sg_cut_out
      tk-multi-snapshot:
        hook_copy_file: default
        hook_scene_operation: default
        hook_thumbnail: default
        location: {name: tk-multi-snapshot, type: app_store, version: v0.2.11}
        template_snapshot: maya_shot_snapshot
        template_work: maya_shot_work
      tk-multi-workfiles:
        allow_task_creation: true
        file_extensions: []
        hook_copy_file: default
        hook_scene_operation: shot_scene_operation_tk_maya
        launch_at_startup: false
        launch_change_work_area_at_startup: false
        location: {name: tk-multi-workfiles, type: app_store, version: v0.3.30}
        saveas_default_name: scene
        saveas_prefer_version_up: false
        sg_entity_type_filters:
          Shot:
          - [sg_status_list, is, ip]
        sg_entity_types: [Shot, Asset]
        template_publish: maya_shot_publish
        template_publish_area: shot_publish_area
        template_work: maya_shot_work
        template_work_area: shot_work_area
    debug_logging: false
    location: {name: tk-maya, type: app_store, version: v0.3.9}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    - {app_instance: tk-multi-snapshot, name: Snapshot...}
    - {app_instance: tk-multi-workfiles, name: Shotgun Save As...}
    - {app_instance: tk-multi-publish-shot, name: Publish Shot...}
    template_project: shot_work_area
    use_sgtk_as_menu_name: false
  tk-nuke:
    apps:
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.14}
      tk-multi-loader:
        button_name: Load Selected Item
        dependency_mode: false
        hook_add_file_to_scene: default
        location: {name: tk-multi-loader, type: app_store, version: v0.2.18}
        menu_name: Load...
        publish_filters: []
        sg_entity_types:
          Shot: []
        single_select: true
        tank_types: [CG Render]
        title_name: Add items to your Scene
      tk-multi-publish:
        display_name: Publish
        hook_copy_file: default
        hook_post_publish: default
        hook_primary_pre_publish: default
        hook_primary_publish: default
        hook_scan_scene: default
        hook_secondary_pre_publish: shot_secondary_pre_publish_tk_nuke
        hook_secondary_publish: shot_secondary_publish_tk_nuke
        hook_thumbnail: default
        location: {name: tk-multi-publish, type: app_store, version: v0.3.15}
        primary_description: Publishes and versions up the current Nuke script.
        primary_display_name: Nuke Publish
        primary_icon: icons/publish_nuke_main.png
        primary_publish_template: nuke_shot_publish
        primary_scene_item_type: work_file
        primary_tank_type: Nuke Script
        secondary_outputs:
        - {description: Publish rendered output, display_group: Publish, display_name: Publish
            Renders, icon: icons/publish_nuke_writenode.png, name: render, publish_template: null,
          required: false, scene_item_type: write_node, selected: false, tank_type: Rendered
            Image}
        - {description: Publish and render on the farm, display_group: Render, display_name: Render
            Network, icon: icons/publish_nuke_writenode.png, name: render_network,
          publish_template: null, required: false, scene_item_type: write_node, selected: false,
          tank_type: Rendered Image}
        template_work: nuke_shot_work
      tk-multi-reviewsubmission:
        location: {name: tk-multi-reviewsubmission, type: app_store, version: v0.1.8}
        movie_height: 540
        movie_path_template: nuke_shot_render_review_mov
        movie_width: 960
        new_version_status: rev
        slate_logo: ''
        store_on_disk: true
        upload_to_shotgun: true
        version_number_padding: 3
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-setframerange:
        location: {name: tk-multi-setframerange, type: app_store, version: v0.1.7}
        sg_in_frame_field: sg_cut_in
        sg_out_frame_field: sg_cut_out
      tk-multi-snapshot:
        hook_copy_file: default
        hook_scene_operation: default
        hook_thumbnail: default
        location: {name: tk-multi-snapshot, type: app_store, version: v0.2.11}
        template_snapshot: nuke_shot_snapshot
        template_work: nuke_shot_work
      tk-multi-workfiles:
        allow_task_creation: true
        file_extensions: []
        hook_copy_file: default
        hook_scene_operation: shot_scene_operation_tk_nuke
        launch_at_startup: false
        launch_change_work_area_at_startup: false
        location: {name: tk-multi-workfiles, type: app_store, version: v0.3.30}
        saveas_default_name: scene
        saveas_prefer_version_up: false
        sg_entity_type_filters:
          Shot:
          - [sg_status_list, is, ip]
        sg_entity_types: [Shot]
        template_publish: nuke_shot_publish
        template_publish_area: shot_publish_area
        template_work: nuke_shot_work
        template_work_area: shot_work_area
      tk-nuke-breakdown:
        hook_multi_update: default
        hook_scan_scene: default
        location: {name: tk-nuke-breakdown, type: app_store, version: v0.2.16}
      tk-nuke-quickdailies:
        current_scene_template: nuke_shot_work
        height: 768
        location: {name: tk-nuke-quickdailies, type: app_store, version: v0.1.8}
        movie_template: shot_quicktime_quick
        post_hooks: [snapshot_history_post_quickdaily]
        sg_version_name_template: nuke_quick_shot_version_name
        width: 1024
      tk-nuke-writenode:
        location: {name: tk-nuke-writenode, type: app_store, version: v0.1.8}
        template_script_work: nuke_shot_work
        write_nodes:
        - file_type: exr
          name: Stereo Exr, 16 bit
          publish_template: nuke_shot_render_exr
          render_template: nuke_shot_render_exr
          settings: {datatype: 16 bit half}
          tank_type: Comp Render
    debug_logging: false
    location: {name: tk-nuke, type: app_store, version: v0.2.16}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    - {app_instance: tk-multi-snapshot, name: Snapshot...}
    - {app_instance: tk-multi-workfiles, name: Shotgun Save As...}
    - {app_instance: tk-multi-publish, name: Publish...}
    use_sgtk_as_menu_name: false
  tk-photoshop:
    apps:
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.14}
      tk-multi-loader:
        button_name: Load Selected Item
        dependency_mode: false
        hook_add_file_to_scene: default
        location: {name: tk-multi-loader, type: app_store, version: v0.2.18}
        menu_name: Load Image...
        publish_filters: []
        sg_entity_types:
          Asset: []
          Shot: []
        single_select: true
        tank_types: [Photoshop Image]
        title_name: Add items to your Scene
      tk-multi-recentfiles:
        hook_add_file_to_scene: default
        launch_at_startup: false
        location: {name: tk-multi-recentfiles, type: app_store, version: v0.2.11}
        template_work: photoshop_shot_work
      tk-multi-screeningroom: '@launch_screeningroom'
    debug_logging: true
    location: {name: tk-photoshop, type: app_store, version: v0.1.5}
  tk-shell:
    apps:
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.14}
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-shotgun-launchmaya: '@launch_maya'
      tk-shotgun-launchnuke: '@launch_nuke'
      tk-shotgun-launchphotoshop: '@launch_photoshop'
    debug_logging: false
    location: {name: tk-shell, type: app_store, version: v0.3.4}
frameworks:
  tk-framework-widget_v0.1.1:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.1}
  tk-framework-widget_v0.1.10:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.10}
  tk-framework-widget_v0.1.12:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.12}
  tk-framework-widget_v0.1.13:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.13}
  tk-framework-widget_v0.1.15:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.15}
  tk-framework-widget_v0.1.16:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.16}
  tk-framework-widget_v0.1.18:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.18}
  tk-framework-widget_v0.1.19:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.19}
  tk-framework-widget_v0.1.20:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.20}
  tk-framework-widget_v0.1.3:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.3}
  tk-framework-widget_v0.1.4:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.4}
  tk-framework-widget_v0.1.5:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.5}
include: ./includes/app_launchers.yml
