description: Apps and Engines related to Shot based work.
engines:
  tk-maya:
    apps:
      tk-maya-breakdown:
        hook_multi_update: default
        hook_scan_scene: default
        location: {name: tk-maya-breakdown, type: app_store, version: v0.2.11}
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.10}
      tk-multi-loader-1:
        button_name: Load Selected Item
        dependency_mode: false
        hook_add_file_to_scene: default
        location: {name: tk-multi-loader, type: app_store, version: v0.2.12}
        menu_name: Load Assets...
        publish_filters: []
        sg_entity_types:
          Asset: []
        single_select: true
        tank_types: [Maya Model, Maya Rig]
        title_name: Add items to your Scene
      tk-multi-loader-2:
        button_name: Load Selected Item
        dependency_mode: false
        hook_add_file_to_scene: default
        location: {name: tk-multi-loader, type: app_store, version: v0.2.12}
        menu_name: Load Shots...
        publish_filters: []
        sg_entity_types:
          Shot: []
        single_select: true
        tank_types: [Maya Anim, Maya Lighting, Maya Scene]
        title_name: Add items to your Scene
      tk-multi-publish:
        display_name: Publish
        hook_copy_file: default
        hook_post_publish: default
        hook_primary_pre_publish: default
        hook_primary_publish: default
        hook_scan_scene: default
        hook_secondary_pre_publish: default
        hook_secondary_publish: default
        hook_thumbnail: default
        location: {name: tk-multi-publish, type: app_store, version: v0.3.2}
        primary_description: Publish and version up the current Maya scene
        primary_display_name: Maya Publish
        primary_icon: icons/publish_maya_main.png
        primary_publish_template: maya_shot_publish
        primary_scene_item_type: work_file
        primary_tank_type: Maya Scene
        secondary_outputs: []
        template_work: maya_shot_work
      tk-multi-publish-extras:
        display_name: Publish with Extras
        hook_copy_file: default
        hook_post_publish: default
        hook_primary_pre_publish: default
        hook_primary_publish: default
        hook_scan_scene: extras_scan_scene_tk-maya
        hook_secondary_pre_publish: extras_secondary_pre_publish_tk-maya
        hook_secondary_publish: extras_secondary_publish_tk-maya
        hook_thumbnail: default
        location: {name: tk-multi-publish, type: app_store, version: v0.3.2}
        primary_description: Publish and version up the current Maya scene
        primary_display_name: Maya Publish
        primary_icon: icons/publish_maya_main.png
        primary_publish_template: maya_shot_publish
        primary_scene_item_type: work_file
        primary_tank_type: Maya Scene
        secondary_outputs:
        - description: 'Publish Alembic Cache data for the assets'
          display_group: Caches
          display_name: Alembic Cache
          icon: 'icons/alembic_output.png'
          name: alembic_cache
          publish_template: cache_alembic
          required: false
          scene_item_type: mesh_group
          selected: false
          tank_type: 'Alembic Cache'
        - description: 'Choose cameras for Playblast'
          display_group: Playblast
          display_name: Playblast
          icon: 'icons/playblast_publish.png'
          name: playblast_publish
          publish_template: maya_shot_review
          required: false
          scene_item_type: shotcam
          selected: false
          tank_type: 'Review Quicktime'
        template_work: maya_shot_work
      tk-multi-recentfiles:
        hook_add_file_to_scene: default
        launch_at_startup: true
        location: {name: tk-multi-recentfiles, type: app_store, version: v0.2.9}
        template_work: maya_shot_work
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-setcontext:
        enable_create_tasks: true
        launch_at_startup: false
        location: {name: tk-multi-setcontext, type: app_store, version: v0.2.7}
        sg_entity_types: [Shot, Asset]
      tk-multi-setframerange:
        location: {name: tk-multi-setframerange, type: app_store, version: v0.1.4}
        sg_in_frame_field: sg_cut_in
        sg_out_frame_field: sg_cut_out
      tk-multi-snapshot:
        hook_copy_file: default
        hook_scene_operation: default
        hook_thumbnail: default
        location: {name: tk-multi-snapshot, type: app_store, version: v0.2.0}
        template_snapshot: maya_shot_snapshot
        template_work: maya_shot_work
      tk-multi-workfiles:
        hook_copy_file: default
        hook_scene_operation: default
        location: {name: tk-multi-workfiles, type: app_store, version: v0.3.3}
        sg_entity_types: [Shot, Asset]
        template_publish: maya_shot_publish
        template_publish_area: shot_publish_area
        template_work: maya_shot_work
        template_work_area: shot_work_area
    debug_logging: false
    location: {name: tk-maya, type: app_store, version: v0.3.4}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    - {app_instance: tk-multi-snapshot, name: Snapshot...}
    - {app_instance: tk-multi-workfiles, name: Shotgun Save As...}
    - {app_instance: tk-multi-publish, name: Publish...}
    template_project: shot_work_area
    use_sgtk_as_menu_name: false
  tk-nuke:
    apps:
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.10}
      tk-multi-loader:
        button_name: Load Selected Item
        dependency_mode: false
        hook_add_file_to_scene: default
        location: {name: tk-multi-loader, type: app_store, version: v0.2.12}
        menu_name: Load...
        publish_filters: []
        sg_entity_types:
          Shot: []
        single_select: true
        tank_types: [Rendered Image]
        title_name: Add items to your Scene
      tk-multi-publish:
        display_name: Publish
        hook_copy_file: default
        hook_post_publish: default
        hook_primary_pre_publish: default
        hook_primary_publish: default
        hook_scan_scene: default
        hook_secondary_pre_publish: default
        hook_secondary_publish: default
        hook_thumbnail: default
        location: {name: tk-multi-publish, type: app_store, version: v0.3.2}
        primary_description: Publishes and versions up the current Nuke script.
        primary_display_name: Nuke Publish
        primary_icon: icons/publish_nuke_main.png
        primary_publish_template: nuke_shot_publish
        primary_scene_item_type: work_file
        primary_tank_type: Nuke Script
        secondary_outputs:
        - {description: Render output from Tank write nodes, display_group: Renders,
          display_name: Nuke Render, icon: icons/publish_nuke_writenode.png, name: render,
          publish_template: null, required: false, scene_item_type: write_node, selected: false,
          tank_type: Rendered Image}
        template_work: nuke_shot_work
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-setframerange:
        location: {name: tk-multi-setframerange, type: app_store, version: v0.1.4}
        sg_in_frame_field: sg_cut_in
        sg_out_frame_field: sg_cut_out
      tk-multi-snapshot:
        hook_copy_file: default
        hook_scene_operation: default
        hook_thumbnail: default
        location: {name: tk-multi-snapshot, type: app_store, version: v0.2.0}
        template_snapshot: nuke_shot_snapshot
        template_work: nuke_shot_work
      tk-multi-workfiles:
        hook_copy_file: default
        hook_scene_operation: default
        location: {name: tk-multi-workfiles, type: app_store, version: v0.3.3}
        sg_entity_types: [Shot, Asset]
        template_publish: nuke_shot_publish
        template_publish_area: shot_publish_area_nuke
        template_work: nuke_shot_work
        template_work_area: shot_work_area_nuke
      tk-nuke-breakdown:
        hook_multi_update: default
        hook_scan_scene: default
        location: {name: tk-nuke-breakdown, type: app_store, version: v0.2.14}
      tk-nuke-quickdailies:
        current_scene_template: nuke_shot_work
        height: 768
        location: {name: tk-nuke-quickdailies, type: app_store, version: v0.1.7}
        movie_template: shot_quicktime_quick
        post_hooks: [snapshot_history_post_quickdaily]
        sg_version_name_template: nuke_quick_shot_version_name
        width: 1024
      tk-nuke-review:
        hook_copy_sequence_file: default
        hook_create_content: default
        hook_scan_scene: default
        location: {name: tk-nuke-review, type: app_store, version: v0.2.3}
        mappings:
        - {input_template: nuke_shot_render_stereo, quicktime_output_template: nuke_shot_render_stereo_review_mov,
          sequence_output_template: nuke_shot_render_stereo_review_seq, version_name_template: nuke_shot_version_name}
        - {input_template: nuke_shot_render_mono_dpx, quicktime_output_template: nuke_shot_render_mono_dpx_review_mov,
          sequence_output_template: nuke_shot_render_mono_dpx_review_seq, version_name_template: nuke_shot_version_name}
      tk-nuke-writenode:
        location: {name: tk-nuke-writenode, type: app_store, version: v0.1.5}
        template_script_work: nuke_shot_work
        write_nodes:
        - file_type: exr
          name: Stereo Exr, 32 bit
          publish_template: nuke_shot_render_pub_stereo
          render_template: nuke_shot_render_stereo
          settings: {datatype: 32 bit float}
          tank_type: Rendered Image
        - file_type: exr
          name: Stereo Exr, 16 bit
          publish_template: nuke_shot_render_pub_stereo
          render_template: nuke_shot_render_stereo
          settings: {datatype: 16 bit half}
          tank_type: Rendered Image
        - file_type: dpx
          name: Mono Dpx
          publish_template: nuke_shot_render_pub_mono_dpx
          render_template: nuke_shot_render_mono_dpx
          settings: {}
          tank_type: Rendered Image
    debug_logging: false
    location: {name: tk-nuke, type: app_store, version: v0.2.12}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    - {app_instance: tk-multi-snapshot, name: Snapshot...}
    - {app_instance: tk-multi-workfiles, name: Shotgun Save As...}
    - {app_instance: tk-multi-publish, name: Publish...}
    - {app_instance: tk-nuke-review, name: Submit for Review...}
    use_sgtk_as_menu_name: false
  tk-photoshop:
    apps:
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.10}
      tk-multi-loader:
        button_name: Load Selected Item
        dependency_mode: false
        hook_add_file_to_scene: default
        location: {name: tk-multi-loader, type: app_store, version: v0.2.12}
        menu_name: Load Image...
        publish_filters: []
        sg_entity_types:
          Asset: []
          Shot: []
        single_select: true
        tank_types: [Photoshop Image]
        title_name: Add items to your Scene
      tk-multi-recentfiles:
        hook_add_file_to_scene: default
        launch_at_startup: false
        location: {name: tk-multi-recentfiles, type: app_store, version: v0.2.9}
        template_work: photoshop_shot_work
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-photoshop-publish:
        hook_publish_file: default
        location: {name: tk-photoshop-publish, type: app_store, version: v0.0.8}
        published_scene_tank_type: Photoshop Image
        template_publish_jpg: photoshop_shot_publish_jpg
        template_publish_psd: photoshop_shot_publish_psd
        template_snapshot: photoshop_shot_snapshot
        template_work: photoshop_shot_work
    debug_logging: true
    location: {name: tk-photoshop, type: app_store, version: v0.0.16}
  tk-shell:
    apps:
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.10}
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-shotgun-launchmaya: '@launch_maya'
      tk-shotgun-launchnuke: '@launch_nuke'
      tk-shotgun-launchphotoshop: '@launch_photoshop'
    debug_logging: false
    location: {name: tk-shell, type: app_store, version: v0.3.1}
frameworks:
  tk-framework-widget_v0.1.1:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.1}
  tk-framework-widget_v0.1.10:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.10}
  tk-framework-widget_v0.1.12:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.12}
  tk-framework-widget_v0.1.13:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.13}
  tk-framework-widget_v0.1.15:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.15}
  tk-framework-widget_v0.1.3:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.3}
  tk-framework-widget_v0.1.4:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.4}
  tk-framework-widget_v0.1.5:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.5}
include: ./includes/app_launchers.yml
