# Shotgun Pipeline Toolkit configuration file
# This file was automatically created by tank clone
# This file reflects the paths in the pipeline configuration
# entity which is associated with this location (Grandpa Dev).

Windows: 'K:\Tank\00719_grandpa\tank'
Darwin: '/core/Tank/00719_grandpa\tank'
Linux: ''

# End of file.
