#
# Copyright (c) 2012 Shotgun Software, Inc
# ----------------------------------------------------

# the type of dynamic content
type: "shotgun_list_field"

# the shotgun entity type to connect to
entity_type: "Asset"

# only make directories for field values which are used
skip_unused: true 

# the shotgun field to use for the folder name
field_name: "sg_asset_type"

