#
# Copyright (c) 2012 Shotgun Software, Inc
# ----------------------------------------------------
#

# Metadata defining the behaviour and requirements for this configuration

# More verbose description of this item 
display_name: "Episodic Show"
description: "Multiroot Storage with Separate Tank Code Root and Separate Roots in Separate Locations"

# Required minimum versions for this item to run
requires_shotgun_version: "v4.3.9"
requires_core_version: "v0.13.21"
 
