description: Apps and Engines related to Asset based work.
engines:
  tk-maya:
    apps:
      tk-maya-breakdown:
        hook_multi_update: default
        hook_scan_scene: default
        location: {name: tk-maya-breakdown, type: app_store, version: v0.2.11}
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.10}
      tk-multi-loader-general:
        button_name: Load Selected Item
        dependency_mode: false
        hook_add_file_to_scene: default
        location: {name: tk-multi-loader, type: app_store, version: v0.2.13}
        menu_name: Load Asset...
        publish_filters: []
        sg_entity_types:
          Asset: []
        single_select: true
        tank_types: []
        title_name: Add items to your Scene
      tk-multi-loader-texture:
        button_name: Load Selected Item
        dependency_mode: false
        hook_add_file_to_scene: default
        location: {name: tk-multi-loader, type: app_store, version: v0.2.13}
        menu_name: Load Texture...
        publish_filters: []
        sg_entity_types:
          Asset: []
        single_select: true
        tank_types: [Diffuse Texture, Specular Texture]
        title_name: Add items to your Scene
      tk-multi-publish:
        display_name: Publish Scene
        hook_copy_file: default
        hook_post_publish: default
        hook_primary_pre_publish: default
        hook_primary_publish: default
        hook_scan_scene: default
        hook_secondary_pre_publish: default
        hook_secondary_publish: default
        hook_thumbnail: default
        location: {name: tk-multi-publish, type: app_store, version: v0.3.10}
        primary_description: Publish and version up the current Maya scene
        primary_display_name: Maya Publish
        primary_icon: icons/publish_maya_main.png
        primary_publish_template: maya_asset_publish
        primary_scene_item_type: work_file
        primary_tank_type: Maya Scene
        secondary_outputs: []
        template_work: maya_asset_work
      tk-multi-publish-asset:
        display_name: Publish Asset
        hook_copy_file: default
        hook_post_publish: default
        hook_primary_pre_publish: shot_asset_primary_pre_publish_tk-maya
        hook_primary_publish: asset_primary_publish
        hook_scan_scene: asset_scan_scene_tk-maya
        hook_secondary_pre_publish: asset_secondary_pre_publish_tk-maya
        hook_secondary_publish: asset_secondary_publish_tk-maya
        hook_thumbnail: default
        location: {name: tk-multi-publish, type: app_store, version: v0.3.10}
        primary_description: Publish and version up the current Maya scene
        primary_display_name: Maya Publish
        primary_icon: icons/publish_maya_main.png
        primary_publish_template: maya_asset_publish
        primary_scene_item_type: work_file
        primary_tank_type: Maya Scene
        secondary_outputs:
        - {description: Choose cameras for Playblast, display_group: Review, display_name: Playblast,
          icon: icons/playblast_publish.png, name: review, publish_template: asset_review_movie,
          required: false, scene_item_type: shotcam, selected: false, tank_type: Review
            Quicktime}
        template_work: maya_asset_work
      tk-multi-publish-model:
        display_name: Publish Model
        hook_copy_file: default
        hook_post_publish: default
        hook_primary_pre_publish: model_primary_pre_publish_tk-maya
        hook_primary_publish: asset_primary_publish
        hook_scan_scene: default
        hook_secondary_pre_publish: default
        hook_secondary_publish: default
        hook_thumbnail: default
        location: {name: tk-multi-publish, type: app_store, version: v0.3.10}
        primary_description: Cleans up and Publishes Model to Shotgun. !!!PLEASE MAKE
          SURE YOU FLATTEN HIERARCHY BEFORE PUBLISHING!!!
        primary_display_name: Maya Publish Model
        primary_icon: icons/publish_maya_main.png
        primary_publish_template: maya_asset_publish
        primary_scene_item_type: work_file
        primary_tank_type: Maya Model
        secondary_outputs: []
        template_work: maya_asset_work
      tk-multi-recentfiles:
        hook_add_file_to_scene: default
        launch_at_startup: false
        location: {name: tk-multi-recentfiles, type: app_store, version: v0.2.9}
        template_work: maya_asset_work
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-setcontext:
        enable_create_tasks: true
        launch_at_startup: false
        location: {name: tk-multi-setcontext, type: app_store, version: v0.2.7}
        sg_entity_types: [Asset]
      tk-multi-snapshot:
        hook_copy_file: default
        hook_scene_operation: default
        hook_thumbnail: default
        location: {name: tk-multi-snapshot, type: app_store, version: v0.2.5}
        template_snapshot: maya_asset_snapshot
        template_work: maya_asset_work
      tk-multi-workfiles:
        file_extensions: []
        hook_copy_file: default
        hook_scene_operation: asset_scene_operation_tk_maya
        launch_at_startup: true
        location: {name: tk-multi-workfiles, type: app_store, version: v0.3.19}
        saveas_default_name: scene
        saveas_prefer_version_up: false
        sg_entity_type_filters: {}
        sg_entity_types: [Asset, Shot]
        template_publish: maya_asset_publish
        template_publish_area: asset_publish_area
        template_work: maya_asset_work
        template_work_area: asset_work_area
    debug_logging: false
    location: {name: tk-maya, type: app_store, version: v0.3.6}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    - {app_instance: tk-multi-snapshot, name: Snapshot...}
    - {app_instance: tk-multi-workfiles, name: Shotgun Save As...}
    - {app_instance: tk-multi-publish-asset, name: Publish Asset...}
    template_project: asset_work_area
    use_sgtk_as_menu_name: false
  tk-nuke:
    apps:
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.10}
      tk-multi-loader:
        button_name: Load Selected Item
        dependency_mode: false
        hook_add_file_to_scene: default
        location: {name: tk-multi-loader, type: app_store, version: v0.2.13}
        menu_name: Load Render...
        publish_filters: []
        sg_entity_types:
          Asset: []
        single_select: true
        tank_types: [Rendered Image]
        title_name: Add items to your Scene
      tk-multi-publish:
        display_name: Publish
        hook_copy_file: default
        hook_post_publish: default
        hook_primary_pre_publish: default
        hook_primary_publish: default
        hook_scan_scene: default
        hook_secondary_pre_publish: default
        hook_secondary_publish: default
        hook_thumbnail: default
        location: {name: tk-multi-publish, type: app_store, version: v0.3.10}
        primary_description: Publishes and versions up the current Nuke script.
        primary_display_name: Nuke Publish
        primary_icon: icons/publish_nuke_main.png
        primary_publish_template: nuke_asset_publish
        primary_scene_item_type: work_file
        primary_tank_type: Nuke Script
        secondary_outputs:
        - {description: Render output from Tank write nodes, display_group: Renders,
          display_name: Nuke Render, icon: icons/publish_nuke_writenode.png, name: render,
          publish_template: null, required: false, scene_item_type: write_node, selected: true,
          tank_type: Rendered Image}
        template_work: nuke_asset_work
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-snapshot:
        hook_copy_file: default
        hook_scene_operation: default
        hook_thumbnail: default
        location: {name: tk-multi-snapshot, type: app_store, version: v0.2.5}
        template_snapshot: nuke_asset_snapshot
        template_work: nuke_asset_work
      tk-multi-workfiles:
        file_extensions: []
        hook_copy_file: default
        hook_scene_operation: default
        location: {name: tk-multi-workfiles, type: app_store, version: v0.3.19}
        saveas_default_name: scene
        saveas_prefer_version_up: false
        sg_entity_type_filters: {}
        sg_entity_types: [Asset]
        template_publish: nuke_asset_publish
        template_publish_area: asset_publish_area
        template_work: nuke_asset_work
        template_work_area: asset_work_area
      tk-nuke-breakdown:
        hook_multi_update: default
        hook_scan_scene: default
        location: {name: tk-nuke-breakdown, type: app_store, version: v0.2.14}
      tk-nuke-quickdailies:
        current_scene_template: nuke_asset_work
        height: 768
        location: {name: tk-nuke-quickdailies, type: app_store, version: v0.1.8}
        movie_template: asset_quicktime_quick
        post_hooks: [snapshot_history_post_quickdaily]
        sg_version_name_template: nuke_quick_asset_version_name
        width: 1024
      tk-nuke-writenode:
        location: {name: tk-nuke-writenode, type: app_store, version: v0.1.7}
        template_script_work: nuke_asset_work
        write_nodes:
        - file_type: exr
          name: Exr
          publish_template: nuke_asset_render_pub
          render_template: nuke_asset_render
          settings: {}
          tank_type: Rendered Image
    debug_logging: false
    location: {name: tk-nuke, type: app_store, version: v0.2.13}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    - {app_instance: tk-multi-snapshot, name: Snapshot...}
    - {app_instance: tk-multi-workfiles, name: Shotgun Save As...}
    - {app_instance: tk-multi-publish, name: Publish...}
    use_sgtk_as_menu_name: false
  tk-photoshop:
    apps:
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.10}
      tk-multi-loader:
        button_name: Load Selected Item
        dependency_mode: false
        hook_add_file_to_scene: default
        location: {name: tk-multi-loader, type: app_store, version: v0.2.13}
        menu_name: Load Image...
        publish_filters: []
        sg_entity_types:
          Asset: []
          Shot: []
        single_select: true
        tank_types: [Photoshop Image]
        title_name: Add items to your Scene
      tk-multi-recentfiles:
        hook_add_file_to_scene: default
        launch_at_startup: false
        location: {name: tk-multi-recentfiles, type: app_store, version: v0.2.9}
        template_work: photoshop_asset_work
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-photoshop-publish:
        hook_publish_file: default
        location: {name: tk-photoshop-publish, type: app_store, version: v0.0.8}
        published_scene_tank_type: Photoshop Image
        template_publish_jpg: photoshop_asset_publish_jpg
        template_publish_psd: photoshop_asset_publish_psd
        template_snapshot: photoshop_asset_snapshot
        template_work: photoshop_asset_work
    debug_logging: true
    location: {name: tk-photoshop, type: app_store, version: v0.1.3}
  tk-shell:
    apps:
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.10}
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-shotgun-launchmaya: '@launch_maya'
      tk-shotgun-launchnuke: '@launch_nuke'
      tk-shotgun-launchphotoshop: '@launch_photoshop'
    debug_logging: false
    location: {name: tk-shell, type: app_store, version: v0.3.3}
frameworks:
  tk-framework-widget_v0.1.1:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.1}
  tk-framework-widget_v0.1.10:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.10}
  tk-framework-widget_v0.1.12:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.12}
  tk-framework-widget_v0.1.13:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.13}
  tk-framework-widget_v0.1.15:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.15}
  tk-framework-widget_v0.1.16:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.16}
  tk-framework-widget_v0.1.3:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.3}
  tk-framework-widget_v0.1.4:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.4}
  tk-framework-widget_v0.1.5:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.5}
include: ./includes/app_launchers.yml
