description: Apps and Engines related to Episode based work.
engines:
  tk-hiero:
    apps:
      tk-hiero-export:
        default_task_template: Basic shot template
        hook_translate_template: default
        location: {name: tk-hiero-export, type: app_store, version: v0.1.1}
        template_nuke_script_path: nuke_shot_work
        template_plate_path: high_resolution_plate
        template_render_path: hiero_nuke_script
      tk-hiero-openinshotgun:
        location: {name: tk-hiero-openinshotgun, type: app_store, version: v0.1.0}
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.10}
      tk-multi-publish:
        display_name: Publish
        hook_copy_file: default
        hook_post_publish: default
        hook_primary_pre_publish: default
        hook_primary_publish: default
        hook_scan_scene: default
        hook_secondary_pre_publish: default
        hook_secondary_publish: default
        hook_thumbnail: default
        location: {name: tk-multi-publish, type: app_store, version: v0.3.4}
        primary_description: Publish and version up the current work file
        primary_display_name: Current Work File
        primary_icon: ''
        primary_publish_template: hiero_publish_project
        primary_scene_item_type: work_file
        primary_tank_type: ''
        secondary_outputs: []
        template_work: hiero_workfile
      tk-multi-recentfiles:
        hook_add_file_to_scene: default
        launch_at_startup: false
        location: {name: tk-multi-recentfiles, type: app_store, version: v0.2.9}
        template_work: hiero_workfile
      tk-multi-setcontext:
        enable_create_tasks: true
        launch_at_startup: false
        location: {name: tk-multi-setcontext, type: app_store, version: v0.2.7}
        sg_entity_types: [Scene]
      tk-multi-workfiles:
        hook_copy_file: default
        hook_scene_operation: default
        location: {name: tk-multi-workfiles, type: app_store, version: v0.3.6}
        sg_entity_types: [Scene]
        template_publish: hiero_publish_project
        template_publish_area: hiero_publish_area
        template_work: hiero_workfile
        template_work_area: hiero_work_area
    debug_logging: false
    location: {name: tk-hiero, type: app_store, version: v0.2.1}
    timeline_context_menu:
    - {app_instance: tk-hiero-openinshotgun, keep_in_menu: false, name: Open in Shotgun, requires_selection: true}
    spreadsheet_context_menu:
    - {app_instance: tk-hiero-openinshotgun, keep_in_menu: false, name: Open in Shotgun, requires_selection: true}
    bin_context_menu: 
    - {app_instance: tk-multi-workfiles, keep_in_menu: true, name: "Shotgun Save As...", requires_selection: true}
    - {app_instance: tk-multi-workfiles, keep_in_menu: true, name: "Version up Current Scene...", requires_selection: true}
    - {app_instance: tk-multi-publish, keep_in_menu: true, name: "Publish Project...", requires_selection: true}
    menu_favourites: 
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
  tk-shell:
    apps:
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.10}
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-shotgun-launchmaya: '@launch_maya'
      tk-shotgun-launchnuke: '@launch_nuke'
      tk-shotgun-launchphotoshop: '@launch_photoshop'
    debug_logging: false
    location: {name: tk-shell, type: app_store, version: v0.3.1}
frameworks:
  tk-framework-widget_v0.1.1:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.1}
  tk-framework-widget_v0.1.10:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.10}
  tk-framework-widget_v0.1.12:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.12}
  tk-framework-widget_v0.1.13:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.13}
  tk-framework-widget_v0.1.15:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.15}
  tk-framework-widget_v0.1.3:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.3}
  tk-framework-widget_v0.1.4:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.4}
  tk-framework-widget_v0.1.5:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.5}
include: ./includes/app_launchers.yml
