description: Apps and engines loaded when an asset or Shot is loaded. Since this configuration
  does not have any configuration on a per shot or per asset basis, there are no apps
  registered in this config. All the work is carried out on a step level. On the shot
  level, the typical workflow is to open the work files app and pick a step and then
  start work.
engines:
  tk-maya:
    apps:
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.10}
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles:
        hook_copy_file: default
        hook_scene_operation: default
        location: {name: tk-multi-workfiles, type: app_store, version: v0.3.6}
        sg_entity_types: [Shot, Asset]
        template_publish: null
        template_publish_area: null
        template_work: null
        template_work_area: null
    debug_logging: false
    location: {name: tk-maya, type: app_store, version: v0.3.5}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    template_project: null
    use_sgtk_as_menu_name: false
  tk-nuke:
    apps:
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.10}
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles:
        hook_copy_file: default
        hook_scene_operation: default
        location: {name: tk-multi-workfiles, type: app_store, version: v0.3.6}
        sg_entity_types: [Shot, Asset]
        template_publish: null
        template_publish_area: null
        template_work: null
        template_work_area: null
    debug_logging: false
    location: {name: tk-nuke, type: app_store, version: v0.2.12}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    use_sgtk_as_menu_name: false
  tk-photoshop:
    apps:
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.10}
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles:
        hook_copy_file: default
        hook_scene_operation: default
        location: {name: tk-multi-workfiles, type: app_store, version: v0.3.6}
        sg_entity_types: [Shot, Asset]
        template_publish: null
        template_publish_area: null
        template_work: null
        template_work_area: null
    debug_logging: true
    location: {name: tk-photoshop, type: app_store, version: v0.1.0}
  tk-shell:
    apps: {tk-shotgun-launchmaya: '@launch_maya', tk-shotgun-launchnuke: '@launch_nuke',
      tk-shotgun-launchphotoshop: '@launch_photoshop'}
    debug_logging: false
    location: {name: tk-shell, type: app_store, version: v0.3.2}
frameworks:
  tk-framework-widget_v0.1.1:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.1}
  tk-framework-widget_v0.1.10:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.10}
  tk-framework-widget_v0.1.12:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.12}
  tk-framework-widget_v0.1.13:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.13}
  tk-framework-widget_v0.1.15:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.15}
  tk-framework-widget_v0.1.3:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.3}
  tk-framework-widget_v0.1.4:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.4}
  tk-framework-widget_v0.1.5:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.5}
include: ./includes/app_launchers.yml
